[package]
name = "mbplox"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/sourcefrog/mbplox"
publish = false

[dependencies]
anyhow = "1.0.44"
argh = "0.1.6"
itertools = "0.10.1"

[dev-dependencies]
assert_cmd = "2.0.1"
pretty_assertions = "1.0.0"
walkdir = "2.0"
